controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    joint_group_position_controller:
      type: position_controllers/JointGroupPositionController
    
    gripper_controller:
      type: position_controllers/JointGroupPositionController

gz_ros_control:
  ros__parameters:
    hold_joints: true
    position_proportional_gain: 0.5

joint_group_position_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    command_interfaces:
      - position

    state_interfaces:
      - position

gripper_controller:
  ros__parameters:
    joints:
      - right_gear_joint
      - right_finger_joint
      - right_pivot_joint
      - left_gear_joint
      - left_finger_joint
      - left_pivot_joint

    command_interfaces:
      - position

    state_interfaces:
      - position